// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rusfasqskkhvxhpxamvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1c2Zhc3Fza2todnhocHhhbXZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMjQ3MjgsImV4cCI6MjA2MzcwMDcyOH0.k8n4bXAGbArwU2khtx0QhvBHe8wi6Fsj9UEuA5P-EbM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);